<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>catch和finally方法</title>
</head>
<body>
    
</body>
<script>
    const p1 = new Promise((resolve,reject)=>{
        throw new Error('run error')//程序运行时抛出错误
        setTimeout(()=>{
            // resolve('ok')
            reject('error')
        },100)
    })
    p1.then((data)=>{
        console.log()
    })
    /*如果异步操作抛出错误,状态就会变为rejected,当then中没有指定rejected状态的回调时就会调用catch方法指定的回调函数

    如果运行中抛出错误,也会被catch方法捕获*/
    .catch(data=>{
        console.log('catch...')
        console.log(data);
    })

    /*finally(回调)
    不管Promise对象最后状态如何,都会执行的操作

    finally方法的回调函数不接受任何参数*/
    .finally(()=>{
        console.log('finally...');
    })
</script>
</html>